# Generated by Django 4.1.7 on 2023-03-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
